INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0001', N'Rừng Na Uy', 'A001', 'C001', 'C011', 'C000', N'Với thủ pháp dòng ý thức, cốt truyện diễn tiến trong dòng hồi tưởng của nhân vật chính là chàng sinh viên bình thường Watanabe Tōru. Cậu ta đã trải qua nhiều cuộc tình chớp nhoáng với nhiều cô gái trẻ ưa tự do. Nhưng cậu ta cũng có những mối tình sâu nặng, điển hình là với Naoko, người yêu của người bạn thân nhất của cậu, một cô gái không ổn định về cảm xúc, và với Midori, một cô gái thẳng thắn và hoạt bát. Các nhân vật trong truyện hầu hết là những con người cô đơn móc nối với nhau. Có những nhân vật đã phải tìm đến cái chết để mãi mãi giải thoát khỏi nỗi đau đớn ấy.
Câu chuyện xảy ra với bối cảnh là nước Nhật những năm 1960, khi mà thanh niên Nhật Bản, như thanh niên nhiều nước khác đương thời, đấu tranh chống lại những định kiến tồn tại trong xã hội. Murakami miêu tả những sinh viên cải cách này như những tên đạo đức giả và thiếu sự kiên định.');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0002', N'Lối sống tối giản của người Nhật', 'A002', 'C002', 'C006', 'C007', N'Chẳng có ai từ khi sinh ra đã có tài sản, đồ đạc gì trong tay. Vậy nên bất cứ ai khi mới chào đời đều là những người sống tối giản. Cứ mỗi lần bạn sở hữu trong tay những đồ dùng hơn mức cần thiết là một lần bạn lấy mất tự do của chính mình. Giá trị bản thân chúng ta không đo bằng những đồ dùng mà chúng ta sở hữu. Những đồ dùng này chỉ cho chúng ta một chút cảm giác hạnh phúc nhất thời mà thôi. Mang theo những đồ dùng hơn mức cần thiết sẽ lấy hết thời gian, năng lượng của bạn. Khi nhận ra được điều đó, tức là bạn đã bắt đầu trở thành một người sống tối giản.');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0003', N'Bố Già', 'A003', 'C001', 'C011', 'C000', N'Bố già là cuốn tiểu thuyết văn học hiện đại Mỹ được đông đảo bạn đọc trên thế giới nói chung và tại Việt Nam nói riêng đón nhận một cách "nồng hậu", và cũng không ngạc nhiên khi bộ phim ra đời ăn theo kịch bản cũng được chào đón nồng nhiệt không kém. Không hẳn là vì cuốn tiểu thuyết viết về cuộc đời của một "trùm mafia" khét tiếng trôi dạt từ hòn đảo Xixili sang đất Mỹ và làm mưa làm gió trên mảnh đất "tự do" này, mà đằng sau đó là những thân phận, những cuộc đời mà lẽ ra vô cùng bình dị và yên ấm như bao gia đình khác. Cái "đế chế vương quyền" bất thành văn ấy, ai đã vào trong, ai đã "cưỡi lên lưng hổ" thì chỉ có con đường tiến, không có đường lui. Là nổ súng, tư thù, đâm thuê chém mướn, tranh giành lãnh địa, tranh hùng tranh bá thiên hạ, vậy mà vẫn ẩn chứa những đằm thắm, mặn mà, nhân hậu và "có thuỷ có chung". Ai đã xây dựng nên, ai là người đại diện xứng đáng, ai danh tiếng lưu truyền? chính là "Bố già - Ông trùm Don Vitô Côrleône".');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0004', N'Sapiens Lược sử loài người','A004','C003', 'C006', 'C013', N'Sapiens, đưa chúng ta vào một chuyến đi kinh ngạc qua toàn bộ lịch sử loài người, từ những gốc rễ tiến hóa của nó đến thời đại của chủ nghĩa tư bản và kỹ thuật di truyền, để khám phá tại sao chúng ta đang trong những điều kiện sinh sống hiện tại.
Sapiens tập trung vào các quá trình quan trọng đã định hình loài người và thế giới quanh nó, chẳng hạn như sự ra đời của sản xuất nông nghiệp, việc tạo ra tiền, sự lan truyền của những tôn giáo, và sự nổi lên của những nhà nước quốc gia. Không giống như những quyển sách khác cùng loại, Sapiens đã có một lối tiếp cận liên ngành học, bắc cầu qua những khoảng cách giữa lịch sử, sinh học, triết học và kinh tế theo một lối trước đây chưa từng có. Hơn nữa, lấy cả quan điểm vĩ mô và vi mô, Sapiens không chỉ đề cập đến những gì đã xảy ra và tại sao, mà còn đi sâu vào việc những cá nhân trong lịch sử đó đã cảm nhận nó như thế nào.')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0005', N'Einstein Cuộc đời và Vũ trụ', 'A005', 'C004', 'C008', 'C000', N'Cuốn sách khai thác và công bố những tư liệu mới nhất về Einstein, làm rõ những giai đoạn, sự kiện và vấn đề trong cuộc sống cá nhân của Einstein. Cuốn sách cũng chỉ ra và làm rõ những chặng trên con đường khoa học của Einstein, cho thấy những suy tư và trăn trở của ông để đưa ra những lý thuyết vật lý làm thay đổi toàn bộ nền vật lý thế kỷ XX, cũng như cuộc tranh luận của ông với các nhà cơ học lượng tử. Tác giả đã lột tả được cá tính, tư tưởng chính trị và những đặc điểm trong trí tuệ, nhân cách của Einstein một cách sinh động.
Nhận định:
"Với tài kể chuyện vô song, Isaacson đã làm nên kỳ tích là vừa giữ được tượng đài Einstein, vừa mang lại cho ông hơi thở sống động, giúp ta cảm thấy như thể ông đang bước đi giữa chúng ta. Đúng là một tác phẩm tuyệt vời" (Doris Kearns Goodwin, tác giả cuốn Team of Rivals [Đội của các đối thủ], No Ordinary Time [Không có thời gian thông thường], và là tác giả đoạt giải Pulitzer về lịch sử.)
"Isaacson đã làm được một việc xuất sắc là truyền tải được cả phần con người lẫn các chi tiết thú vị trong cuộc đời khoa học của Einstein. Đây không chỉ là một cuốn tiểu sử hấp dẫn, mà mỗi trang luôn mời chào ta đọc trang tiếp theo, mà còn là một tác phẩm tiêu biểu hàng đầu trong thể loại phi hư cấu." (Lawrence M. Krauss, Giáo sư vật lý theo chương trình Ambrose Swasey tại Đại học Case Western Reserve và là tác giả của cuốn Hiding in the Mirror [Trốn trong gương]) Isaacson đã viết một cuốn tiểu sử chính xác, hấp dẫn và thú vị, trình bày thật khéo các văn liệu lịch sử và đưa đến nhiều hiểu biết mới mẻ về cuộc đời cũng như sự nghiệp của Einstein (Diana Kormos Buchwald, chủ biên cuốn Tuyển tập các bài nghiên cứu của Albert Einstein và là Giáo sư lịch sử tại Caltech)')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0006', N'Tôi thấy hoa vàng trên cỏ xanh', 'A006', 'C001', 'C020', 'C000', N'Truyện Tối Thấy Hoa Vàng Trên Cỏ Xanh hiện đang là một bộ truyện đang được truy lùng nhiều nhất để đọc vì sau khi xem bộ phim đã được dựng nên người xem vẫn chưa thỏa mãn được nội dung mà tác giả Nguyễn Nhật Ánh truyền tải.
Nội dung truyện nói về tuổi thơ nghèo khó của hai anh em Thiều và Tường ở một làng quê Việt thân thuộc và nên thơ. Là nơi đã chứng kiến những rung động đầu đời của cả hai, tình cảm gia đình, tình anh em yêu thương chân thành, cũng như những đố kỵ, ghen tuông và những nỗi đau trong veo trong quá trình trưởng thành.')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0007', N'Harry Potter và hòn đá phù thủy', 'A007' ,'C001', 'C020', 'C000', N'Harry Potter và Hòn đá Phù thủy (tiếng Anh: Harry Potter and the Philosophers Stone) là tác phẩm đầu tiên trong bộ truyện Harry Potter gồm 7 tập của nữ văn sĩ người Anh J. K. Rowling. Quyển sách đã được xuất bản ngày 30 tháng 6 năm 1997 bởi nhà bản Bloomsbury.Đây là một tập truyện quan trọng, bởi nó đặt nền tảng cho 6 tập tiếp theo. Nó giúp ta bước đầu khám phá thế giới Pháp thuật của Harry Potter, làm quen với các nhân vật chính, địa điểm, với một số thuật ngữ... Tập đầu tiên này đưa ra những câu hỏi chưa có câu trả lời, bằng những dấu hiệu cho những tình tiết trong các tập tiếp theo, tạo cho độc giả sự tò mò.')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0008', N'Những kẻ xuất chúng', 'A008', 'C005', 'C006', 'C000', N'Cuốn sách Những kẻ xuất chúng sẽ giúp bạn tìm ra câu trả lời thông qua các phân tích về xã hội, văn hóa và thế hệ của những nhân vật kiệt xuất như Bill Gates, Beatles và Mozart, bên cạnh những thất bại đáng kinh ngạc của một số người khác (ví dụ: Christopher Langan, người có chỉ số IQ cao hơn Einstein nhưng rốt cuộc lại quay về làm việc trong một trại ngựa). Theo đó, cùng với tài năng và tham vọng, những người thành công đều được thừa hưởng một cơ hội đặt biệt để rèn luyện kỹ năng và cho phép họ vượt lên những người cùng trang lứa.')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0009', N'Súng, Vi Trùng và Thép', 'A009', 'C003', 'C006', 'C000', N'“Súng, vi trùng và thép: Định mệnh của các xã hội loài người” là cuốn sách khoa học phổ thông thứ hai và nổi tiếng nhất của Jared Diamond, được xuất bản lần đầu trên thế giới vào năm 1997.
Cuốn sách đã trở thành cuốn sách bán chạy nhất trên thế giới thời điểm đó, được dịch ra 33 thứ tiếng và nhận được nhiều giải thưởng, trong đó có một giải Pulitzer, một giải thưởng Sách Khoa học Aventis và giải thưởng Khoa học Phi Beta Kappa năm 1997. Một bộ phim tài liệu truyền hình nhiều tập dựa trên cuốn sách đã được Hiệp hội Địa lý Quốc gia sản xuất vào năm 2005.
Đến nay, "Súng, vi trùng và thép" đã bán được hàng triệu bản và vẫn được xem là một công trình nền tảng về địa lý liên ngành, toàn diện và đột phá.
Yuval Harari đã lấy cảm hứng từ chính cuốn sách này của Jared Diamond để sáng tác ra một cuốn sách nổi tiếng không kém: “Sapiens: Lược sử về loài người”. Colin Renfrew – Thành viên Quốc hội Vương quốc Liên hiệp Anh và Bắc Ireland nhận xét: “Diamond đã viết nên một tác phẩm với tầm tri thức đặc biệt xuất sắc. Đây là một trong những công trình quan trọng nhất và đáng đọc nhất về loài người”.')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0010', N'Tư Duy Nhanh Và Chậm', 'A010','C005', 'C006', 'C000', N'“Tư duy nhanh và chậm”, cuốn sách nổi tiếng tổng hợp tất cả nghiên cứu được tiến hành qua nhiều thập kỷ của nhà tâm lý học từng đạt giải Nobel Kinh tế Daniel Kahneman sẽ cho bạn thấy những sư hợp lý và phi lý trong tư duy của chính bạn. Cuốn sách được đánh giá là “kiệt tác” trong việc thay đổi hành vi của con người, Tư duy nhanh và chậm đã dành được vô số giải thưởng danh giá, lọt vào Top 11 cuốn sách kinh doanh hấp dẫn nhất năm 2011. Alpha Books đã mua bản quyền và sẽ xuất bản cuốn sách trong Quý 1 năm nay. Tư duy nhanh và chậm dù là cuốn sách có tính hàn lâm cao nhưng vô cùng bổ ích với tất cả mọi người và đặc biệt rất dễ hiểu và vui nhộn.
Đã có rất nhiều cuốn sách nói về tính hợp lý và phi lý của con người trong tư duy, trong việc đánh giá và ra quyết định, nhưng Tư duy nhanh và chậm được Tạp chí Tài chính Mỹ đánh giá là “kiệt tác”.')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0011', N'Khi hơi thở hóa thinh không', 'A011','C008', 'C004', 'C000', N'Khi Hơi Thở Hóa Thinh Không là tự truyện của một bác sĩ bị mắc bệnh ung thư phổi. Trong cuốn sách này, tác giả đã chia sẻ những trải nghiệm từ khi mới bắt đầu học ngành y, tiếp xúc với bệnh nhân cho tới khi phát hiện ra mình bị ung thư và phải điều trị lâu dài.
Kalanithi rất yêu thích văn chương nên câu chuyện của anh đã được thuật lại theo một phong cách mượt mà, dung dị và đầy cảm xúc. Độc giả cũng được hiểu thêm về triết lý sống, triết lý nghề y của Kalanithi, thông qua ký ức về những ngày anh còn là sinh viên, rồi thực tập, cho đến khi chính thức hành nghề phẫu thuật thần kinh. “Đối với bệnh nhân và gia đình, phẫu thuật não là sự kiện bi thảm nhất mà họ từng phải đối mặt và nó có tác động như bất kỳ một biến cố lớn lao trong đời. Trong những thời điểm nguy cấp đó, câu hỏi không chỉ đơn thuần là sống hay chết mà còn là cuộc sống nào đáng sống.” – Kalanithi luôn biết cách đưa vào câu chuyện những suy nghĩ sâu sắc và đầy sự đồng cảm như thế.')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0012', N'Khi hơi thở hóa thinh không', 'A012','C006', 'C010', 'C000', N'Tò mò là một trong những phẩm chất bẩm sinh vô cùng quan trọng của chúng ta, và những vấn đề như Bản chất của vũ trụ là gì? Vũ trụ từ đâu ra? Chúng ta đến từ đâu và đóng vai trò gì trong vũ trụ? Có giới hạn cho sự nhận thức của con người không?... là những câu hỏi mà biết bao nhiêu thế hệ con người đã đặt ra dưới dạng này hoặc dạng khác từ khi bắt đầu biết nhận thức và suy ngẫm về thế giới này. Tất cả những vấn đề được nên ra trong tác phẩm Lược sử thời gian như Vũ trụ giãn nở, Lỗ đen, Nguồn gốc và số phận của vũ trụ, Mũi tên thời gian… đều là mong muốn của tác giả để phần nào trả lời được những câu hỏi đó, và hướng tới việc giải thích các giai đoạn lịch sử của toàn bộ vũ trụ.
Bằng ngôn ngữ sáng sủa, lập luận chặt chẽ rất thuyết phục, và sự dí dỏm rất riêng, tác giả Stephen Hawking đặt ra cho mình nhiệm vụ diễn tả những điều phức tạp nhất trong vật lý học một cách dễ hiểu đối với mọi người, không dùng bất kỳ công thức toán học nào, trừ phương trình nổi tiếng của Einstein: E = mc2')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0013', N'Tôi Nói Gì Khi Nói Về Chạy Bộ', 'A001','C008', 'C004', 'C000', N'Murakami đã nói thế này trong cuốn sách của mình: “Chạy bộ có rất nhiều ưu điểm, trước hết, ta không cần có thêm ai mới được, và không cần thiết bị đặc biệt. Ta không phải đến một nơi đặc biệt nào để chạy cả. Chỉ cần có giày chạy bộ và một con đường tốt là có thể chạy tùy thích”. 
Đúng thế, nó là môn thể thao đại chúng, cho tất cả mọi người. Ai cũng có thể bắt đầu.')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0014', N'Những Tù Nhân Của Địa Lý', 'A014','C003', 'C012', 'C000', N'Cuốn sách gồm 10 chương cũng là 10 vị trí địa lý nóng mang tính quyết định cao trong việc vận hành trật tự trái đất theo cách của con người. Trước hết, Những Tù Nhân Của Địa Lý không phải là một cuốn sách khô khan về địa lý hay chính trị. Tim đã rất tài tình trong việc sử dụng câu chữ cuốn hút độc giả theo cách kể chuyện của một người đầy hiểu biết và trải nghiệm thực tế.
Nội dung chính của Những Tù Nhân Của Địa Lý là chủ đề Địa chính trị. Mối liên hệ trực tiếp giữa địa lý các quốc gia, điều kiện tự nhiên của lãnh thổ tương tác với yếu tố quyền lực của những người vận hành. Tài nguyên dầu mỏ đã tác động đến nền kinh tế thế giới và tham gia vào việc phân chia vị thế các quốc gia như thế nào?
Sách như vừa dẫn dắt bạn đi du lịch, khám phá những vùng miền thường được nhắc tới lại lồng ghép các sự kiện lịch sử lớn. Và điều hấp dẫn đó là tất cả các yếu tố đó để lý giải quá khứ cũng như dự đoán tương lai chung sống của con người.')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0015', N'Nguồn gốc các loài', 'A014','C006', 'C011', 'C000', N'Nguồn Gốc Các Loài 
là tên rút gọn của cuốn sách Về Nguồn Gốc Các Loài Qua Con Đường Chọn Lọc Tự Nhiên, hay Sự Bảo Tồn Những Chủng Ưu Thế Trong Đấu Tranh Sinh Tồn (của Charles Darwin, xuất bản năm 1859). Đây là một cuốn sách khoa học hiếm có khi bán hết 1250 bản in lần đầu trong vòng một ngày và trong một thời gian ngắn đã làm “rung chuyển” cả thế giới. Cuốn sách này là kết quả của những quan sát của Darwin trong chuyến đi gần 5 năm, từ 1831 đến 1836, trên con tàu biển Beagle vòng quanh thế giới, cùng với những suy tư và nghiên cứu của ông trong hai mươi năm sau đó, trong đó ông đặt vấn đề có tính quyết định về biến đổi luận hay sự tiến hóa. Sách của ông đã được xuất bản nhiều lần, sửa đổi, liên tục cập nhật cho đến khi ông mất.')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0016', N'Thiên nga đen: Xác suất cực nhỏ - tác động cực lớn', 'A015','C006', 'C014', 'C000', N'Thiên nga đen giúp chúng ta hiểu sâu sắc về việc nhìn nhận sự ngẫu nhiên và những hạn chế mà con người gặp phải trong việc đưa ra các dự đoán.
Chính do quá tin tưởng vào trực giác khiến mất đi tính chính xác, không có khả năng để hiểu và xác định sự ngẫu nhiên, và thậm chí do cả cơ chế sinh học trong mỗi người đã khiến ta đưa ra các quyết định sai lầm, và đôi khi dẫn đến hiện tượng "Thiên nga đen" - sự cố được cho là không thể xảy ra nhưng lại xác lập lại hiểu biết của chúng ta về thế giới.')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0017', N'Nhật Kí Anne Frank', 'A016','C006', 'C011', 'C003', N'Nhật Ký Anne Frank – cuốn nhật ký của cô bé người Hà Lan đã gây xúc động trên toàn thế giới, kể về những ngày tháng cùng gia đình chạy trốn mũi súng của quân Hitler. Sách được UNESCO vinh danh là một trong mười cuốn sách được đọc rộng rãi nhất trên toàn thế giới vì những giá trị hết sức nhân văn của mình.')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0018', N'Nguoi Xa La', 'A017','C006', 'C011', 'C018', N'Người xa lạ của Albert Camus được khởi thảo năm 1938, hoàn tất năm 1940 và xuất bản lần đầu năm 1942. Tiểu thuyết khắc họa chân dung nhân vật Meursault trong khoảng thời gian kể từ ngày mẹ của Meursault chết ở trại tế bần dành cho người già cho đến gần cái chết của chính anh ta. Cuốn sách được chia thành 2 phần với 11 chương, với kiểu tự thuật về cuộc đời của nhân vật tôi - Meursault, một nhân viên thư ký lãnh việc gửi hàng hóa. Anh ta sống cô độc, nhận được tin mẹ mất, “Mẹ đã chết hôm nay. Hay là hôm qua nhỉ, tôi không rõ.” Anh ta đi dự đám tang, rồi lại tới sở làm, đi bơi, xem xi-nê,… đi chơi với người yêu và giết người tại bãi biển. Meursault bị lên án vì không có biểu hiện của một người con mất mẹ (không thăm mẹ thường xuyên, không đau khổ, không nhìn mặt mẹ lần cuối, uống cà phê và hút thuốc trước quan tài người chết, ngủ trong khi canh linh cữu, xem phim hài và hành động yêu đương chỉ một ngày sau khi mẹ mất…), bị công tố viên buộc tội vì “đã chôn cất bà mẹ bằng trái tim của một kẻ sát nhân.” Câu chuyện mở đầu bằng cái chết, phân tách hai phần bằng cái chết và kết thúc bằng một án tử hình.')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0019', N'Nhà Giả Kim', 'A018','C001', 'C011', 'C018', N'Tiểu thuyết Nhà giả kim của Paulo Coelho như một câu chuyện cổ tích giản dị, nhân ái, giàu chất thơ, thấm đẫm những minh triết huyền bí của phương Đông. Trong lần xuất bản đầu tiên tại Brazil vào năm 1988, sách chỉ bán được 900 bản. Nhưng, với số phận đặc biệt của cuốn sách dành cho toàn nhân loại, vượt ra ngoài biên giới quốc gia, Nhà giả kim đã làm rung động hàng triệu tâm hồn, trở thành một trong những cuốn sách bán chạy nhất mọi thời đại, và có thể làm thay đổi cuộc đời người đọc.')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0020', N'Vũ Trụ', 'A019','C009', 'C006', 'C000', N'Mười ba câu chuyện tuyệt đẹp về Vũ trụ. Qua lời kể trữ tình của Carl Sagan, người đọc sẽ có dịp du hành trong vũ trụ, khám phá thế giới từ vĩ mô của những thiên hà to lớn đến thế giới vi mô của những con vi khuẩn nhỏ bé trên Trái đất, đi từ những nền văn minh xa xưa đến tương lai của thế giới, cho ta thấy mối gắn bó hữu cơ của từng sự việc nhỏ nhặt với vũ trụ bao la và nghe những giọng điệu nhiều bè của Vũ trụ. Vũ trụ đã chỉ là vũ trụ vô tri, hỗn độn, mà còn là một thế giới có trật tự, có tri giác, đầy nhân văn và xúc cảm. Cuốn sách của Carl Sagan, một nhà thiên văn học nổi tiếng đã bán được hơn 5 triệu bản trên toàn thế giới.')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0021', N'Homo Deus: Lược sử tương lai', 'A004','C006', 'C003', 'C000', N'Homo sapiens có phải là một dạng sống siêu đẳng, hay chỉ là một tay đầu gấu địa phương? Làm thế nào con người lại tin rằng họ không chỉ đã kiểm soát thế giới, mà còn mang lại ý nghĩa cho nó? Công nghệ sinh học và trí thông minh nhân tạo đe doạ loài người ra sao? Sinh vật nào có thể kế thừa loài người, và tôn giáo mới nào sẽ được sản sinh?
Với giọng kể cuốn hút và mới lạ, Harari sẽ dần gợi mở và trả lời những câu hỏi trê, nhờ phân tích chi tiết những luận điểm gây nhiều tranh cãi: chủ nghĩa nhân đạo là một dạng tôn giáo, thứ tôn giáo tôn thờ con người thay vì thần thánh; sinh vật là thuật toán… ông vẽ ra một viễn cảnh tương lai khi Sapiens thất thế và Dữ liệu giáo trở thành một hình mẫu. HOMO DEUS còn bàn sâu hơn về các năng lực mà con người đã tự trang bị để sinh tồn và tiến hoá thành một giống loài ngự trị trên trái đất, để rồi chính trong tiến trình hoàn thiện và nâng cấp các năng lực ấy chúng ta sẽ bị truất quyền kiểm soát bởi một sinh vật mới, mang tên Homo Deus.')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0022', N'Sữa và mật', 'A021','C020', 'C020', 'C000', N'Sữa và mật được chia thành bốn chương tương đương với bốn chủ đề: đau, yêu, vỡ, lành, tựa như một hành trình trải nghiệm cuộc sống của người thiếu nữ vừa biết yêu, mang theo trong mình tràn đầy nồng nàn, trải qua vết đau rồi bước đến với ánh sáng của sự chữa lành, an ủi. Tất cả trải nghiệm đều được thể hiện bằng thứ ngôn ngữ đầy nữ tính vừa đáo để vừa nồng nàn của Kaur.')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0023', N'Thơ Xuân Diệu', 'A021','C019', 'C020', 'C000', N'Trong sự nghiệp sáng tác thơ văn của mình, Xuân Diệu được biết đến như là một nhà thơ lãng mạn trữ tình, “Nhà thơ mới nhất trong các nhà thơ mới” (Hoài Thanh), “Ông hoàng của thơ tình”.
Xuân Diệu là thành viên của Tự Lực Văn Đoàn và cũng đã là một trong những chủ soái của phong trào “Thơ Mới”. Tác phẩm tiêu biểu của ông ở giai đoạn này: Thơ Thơ (1938), Gửi hương cho gió (1945), truyện ngắn Phấn thông vàng (1939), Trường ca (1945).
Xuân Diệu tham gia ban chấp hành, nhiều năm là ủy viên thường vụ Hội Nhà văn Việt Nam. Từ đó, Xuân Diệu trở thành một trong những nhà thơ hàng đầu ca ngợi Cách mạng, một “dòng thơ công dân”. Bút pháp của ông chuyển biến phong phú về giọng vẻ: có giọng trầm hùng, tráng ca, có giọng chính luận, giọng thơ tự sự trữ tình. Tiêu biểu là: Ngọn quốc kỳ (1945), Một khối hồng (1964), Thanh ca (1982), Tuyển tập Xuân Diệu (1983).')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0024', N'Truyện Kiều', 'A022','C019', 'C011', 'C001', N'Gần 200 năm nay, Truyền Kiều đã chiếm một vị trí đặc biệt trong đời sống tinh thần của người dân Việt Nam. Có rất nhiều đề tài nghiên cứu lớn về các vấn đề xoay quanh Truyện Kiều. Các thế hệ cứ lần lượt nối tiếp nhau qua những trang Kiều. Truyện Kiều thực sự đã đi vào thi ca, nhạc họa và nếp sống của con người tự bao giờ. Truyện Kiều còn vươn xa hơn nữa khi được những các nhà xuất bản nước ngoài trân trọng dịch ra nhiều ngôn ngữ: Tiếng Anh, tiếng Pháp, tiếng ĐứC
Trải qua thời gian, ngày càng có nhiều nghiên cứu phát hiện mới về Truyện Kiều. Trong cuốn sách này, cung cấp thêm cho độc giả những hiểu biết về đại thi hào Nguyễn Du, những khảo dị và những câu chuyện dân gian về nàng Kiều theo sự nghiên cứu và sưu tầm của Giáo sư Vũ Ngọc Khánh. Hy vọng, với cuốn Truyện Kiều này, độc giả sẽ tìm hiểu được những thông tin thú vị.')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0025', N'Dế mèn phiêu lưu kí', 'A023','C001', 'C021', 'C011', N'Dế mèn phiêu lưu ký là truyện dài của nhà văn Tô Hoài kể về cuộc phiêu lưu của chú Dế Mèn cùng các bạn bè.
Trên đường đi, họ đã gặp phải nhiều khó khăn nguy hiểm, nhưng những gian nan đã cho họ nhiều bài học quý giá, và thắt chặt tình bạn của họ. 
Ngoài việc khuyến khích những người trẻ tuổi dám mơ ước, dám hành động, truyện còn là khát vọng hoà bình giữa các loài, là mong ước anh em bốn bể có thể cùng chung sống hoà thuận, để thế giới không còn cảnh xung đột, thù ghét.')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0026', N'Tuổi Thơ Dữ Dội', 'A024','C001', 'C021', 'C000', N'Nhắc đến Phùng Quán, người ta sẽ nhớ ngay tới một cây bút lạ kỳ trong nền văn học Việt Nam với một tác phẩm thiếu nhi vô cùng chân thực và xúc động về một thế hệ trẻ anh hùng:
Tuổi thơ dữ dội - cuốn truyện xoay quanh cuộc sống chiến đấu và hy sinh của những thiếu niên 13, 14 tuổi trong hàng ngũ Đội thiếu niên trinh sát của trung đoàn Trần Cao Vân. Những Lượm, Mừng, Quỳnh sơn ca, Hòa đen, Bồng da rắn, Vịnh sưa, Tư dát... mỗi người một hoàn cảnh song đều chung quyết tâm, nhiệt huyết và lòng yêu nước, đã tham gia chiến đấu hết mình và hy sinh khi tuổi đời còn rất trẻ.
Đúng như tên truyện, độc giả sẽ bắt gặp ở đó những chi tiết thực sự dữ dội về cuộc đời thiếu niên bất hạnh, về cuộc chiến tranh chống giặc tàn khốc nhưng ẩn sâu bên trong ta vẫn thấy những tâm hồn trong sáng và vô tư, thấy sự can trường, dũng cảm phi thường của nhân vật. Tất cả những ai đã từng đọc tác phẩm này hầu như đều không ngăn được xúc động và những giọt nước mắt cảm thương, cảm phục. Đây thực sự là một tác phẩm quý trong kho tàng văn học Việt Nam. Một câu chuyện khơi dậy trong mỗi người tình yêu đất nước và niềm trân trọng ký ức tuổi thơ...')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0027', N'Cánh đồng bất tận', 'A025','C001', 'C022', 'C000', N'Cánh đồng bất tận bao gồm những truyện hay và mới nhất của nhà văn Nguyễn Ngọc Tư. Đây là tác phẩm đang gây xôn xao trong đời sống văn học, bởi ở đó người ta tìm thấy sự dữ dội, khốc liệt của đời sống thôn dã qua cái nhìn của một cô gái. Bi kịch về nỗi mất mát, sự cô đơn được đẩy lên đến tận cùng, khiến người đọc có lúc cảm thấy nhói tim…')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0028', N'Mắt biếc', 'A006','C001', 'C023', 'C000', N'"Mắt Biếc" là câu chuyện kể về cuộc đời của nhân vật Ngạn. Sinh ra và lớn lên ở một ngôi làn tên Đo Đo (cũng là nguyên quán của Nguyễn Nhật Ánh - tác giả), Ngạn thầm yêu từ nhỏ cô nàng cùng xóm có đôi mắt tuyệt đẹp - Hà Lan. Tuổi thơ ở nơi làng xóm bình yên giản dị thật là đẹp, nhưng rồi cũng đến lúc kết thúc khi cả hai đều phải lên thành phố tiếp tục việc học, và tấm bi kịch bắt đầu từ đây.
Lòng thương nhớ của Ngạn đối với Hà Lan vẫn luôn không thay đổi, nhưng cô gái ấy đã không thể chống lại sự cám dỗ của thị thành, cô đã ngã vào lòng một người con trai khác tên Dũng. Cô và Dũng có con, nhưng người đàn ông ấy đã ruồng bỏ cô, khiến cô phải gửi đứa trẻ về quê cho bà ngoại chăm sóc, cô đặt tên nó là Trà Long. Hà Lan vẫn biết Ngạn thầm thương mình bấy lâu, nhưng cô không chấp nhận vì cô biết, cô và Ngạn không cùng một lối sống. Thế nhưng tấm lòng của anh trai làng vẫn không hề thay đổi, anh dành hết tình thương cho con cô. Cô bé Trà Long ấy ngày một lớn và trở thành cô giáo, và tất nhiên, cô rất quý mến Ngạn.Liệu, Trà Long có phải là những gì mà Ngạn tìm kiếm ở Hà Lan,người có bù đắp lại những thứ mà Ngạn đã bỏ dở trong cuộc đời anh ấy?...')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0029', N'Tuổi Trẻ Đáng Giá Bao Nhiêu', 'A026','C005', 'C006', 'C000', N'Tuổi Trẻ Đáng Giá Bao Nhiêu
"Bạn hối tiếc vì không nắm bắt lấy một cơ hội nào đó, chẳng có ai phải mất ngủ.
Bạn trải qua những ngày tháng nhạt nhẽo với công việc bạn căm ghét, người ta chẳng hề bận lòng.
Bạn có chết mòn nơi xó tường với những ước mơ dang dở, đó không phải là việc của họ.
Suy cho cùng, quyết định là ở bạn. Muốn có điều gì hay không là tùy bạn.
Nên hãy làm những điều bạn thích. Hãy đi theo tiếng nói trái tim. Hãy sống theo cách bạn cho là mình nên sống.
Vì sau tất cả, chẳng ai quan tâm."')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0030', N'Chiến Tranh và Hòa Bình', 'A027','C011', 'C001', 'C000', N'Bộ sách CHIẾN TRANH VÀ HÒA BÌNH của Đại Văn hào người Nga Lev Tolstoi được xem là một kiệt tác văn chương. Tác phẩm phản ánh một giai đoạn bi tráng của toàn xã hội Nga, từ giới quý tộc đến nông dân.
CHIẾN TRANH VÀ HÒA BÌNH mở đầu với khung cảnh một buổi tiếp tân, nơi có đủ mặt các nhân vật sang trọng của giới quý tộc Nga tại kinh kỳ Sankt-Peterburg. Bên cạnh những câu chuyện thường nhật của giới quý tộc, người ta bắt đầu nhắc đến Hoàng đế Napoléon I và cuộc chiến tranh chống Pháp sắp tới mà Nga sắp tham gia.
Trong số những tân khách hôm ấy có công tước Andrei Bolkonsky - một người trẻ tuổi, đẹp trai, giàu có, có cô vợ Liza xinh đẹp mới cưới và đang chờ đón đứa con đầu lòng. Và một vị khách khác là Pierre người con rơi của lão bá tước Bezoukhov, vừa từ nước ngoài trở về. Tuy khác nhau về tính cách, một người khắc khổ về lý trí, một người hồn nhiên sôi nổi song Andrei và Pierre rất quý mến nhau và đều là những chàng trai trung thực, luôn khát khao đi tìm lẽ sống. Andrei tuy giàu có và thành đạt nhưng chán ghét tất cả nên chàng chuẩn bị nhập ngũ với hy vọng tìm được chỗ đứng của một người đàn ông chân chính nơi chiến trường. Còn Pierre từ nước ngoài trở về nước Nga, tham gia vào các cuộc chơi bời và bị trục xuất khỏi Sankt-Peterburg vì tội du đãng. Pierre trở về cố đô Moskva, nơi cha chàng đang sắp chết. Lão bá tước Bezoukhov rất giàu có, không có con, chỉ có Pierre là đứa con rơi mà ông chưa công nhận… ')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0031', N'Đông Chu Liệt Quốc', 'A028','C011', 'C001', 'C000', N'Đông Chu liệt quốc là bộ tiểu thuyết đồ sộ gồm 108 hồi, phản ánh giai đoạn 550 năm bão táp của lịch sử Trung Hoa từ thời Xuân Thu đến Chiến Quốc. Năm thế kỉ tranh hùng đồ bá ấy với hàng trăm sự kiện và nhân vật được miêu tả sống động mà gãy gọn, lúc căng lúc chùng, lúc lên lúc xuống. Dưới ngòi bút tinh mĩ ấy, trước tác của Phùng Mộng Long không còn gói gọn trong khuôn khổ của những tiểu thuyết “diễn nghĩa” đương thời mà đã trở thành một kho sử liệu ngồn ngộn nhưng rành rẽ, tạo được niềm say mê, thích thú đối với độc giả.')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0032', N'Tam Quốc Diễn Nghĩa', 'A029','C011', 'C001', 'C000', N'Nền văn hiến Trung Hoa có lịch sử phát triển lâu đời, sở hữu một kho tàng văn học cổ điển đồ sộ, phong phú có sự giao thoa và ảnh hưởng mật thiết đối với nền văn học truyền thống Việt Nam. Khá nhiều tác phẩm nổi tiếng của văn học Trung Hoa từ rất lâu đã rất quen thuộc với người đọc Việt.
Trong lĩnh vực văn xuôi, tiểu thuyết chương hồi đã phát triển đến trình độ huy hoàng, để lại rất nhiều trước tác bất hủ lừng danh thế giới mà nổi bật nhất là Tứ đại kỳ thư, mà nổi bật nhất là Tứ đại kỳ thư gồm:Tam quốc diễn nghĩa, Thủy hử, Tây du ký, Hồng lâu mộng – bốn đỉnh cao rực rỡ của văn học cổ điển Trung Hoa. Bên cạnh đó, còn rất nhiều những pho tiểu thuyết đặc sắc khác từ lâu đã trở thành kinh điển, như Liêu trai chí dị, Dương gia tướng, Phong thần diễn nghĩa… Những tác phẩm cổ điển đó luôn lấp lánh một vẻ đẹp thần bí khó cưỡng, như ánh hào quang tỏa ra từ kho báu ngàn xưa, đang chờ chúng ta khám phá.')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0033', N'Cỏ Ven Đường', 'A030','C011', 'C001', 'C000', N'Natsume Sōseki (1867 - 1916), là “một trong ba trụ cột của văn học hiện đại Nhật Bản” bên cạnh Mori Ōgai và Akutagawa Ryunosuke. Nổi tiếng vì thuộc thế hệ trí thức tinh hoa Nhật Bản trong thời kỳ Meiji, ông là nhà văn có sức ảnh hưởng lớn đến các thế hệ văn chương về sau, dẫn đến việc hình thành trường phái Sōseki, phái văn chương Tâm lý cao sang.
Trong các tác phẩm của ông, Cỏ ven đường (viết và đăng nhiều kỳ trên mặt báo Asahi từ tháng 6 đến tháng 9/1915) được xem là một kiểu tự truyện của Natsume Sōseki, có lẽ vì Kenzō, nhân vật chính trong truyện, có rất nhiều chi tiết gần gũi với ông. Là một người làm nghề dạy học nhưng Kenzō chỉ muốn dành hết thời gian cá nhân cho việc đọc và viết trong không gian tĩnh lặng của thư phòng. Kenzō tự biết mình là kẻ vô dụng trong những công việc của cuộc sống đời thường, vì điều đó được thể hiện quá rõ trong cái nhìn của mọi người xung quanh hướng vào anh. Kenzō cũng biết là mình có đời sống vật chất nghèo nàn, khi chiếc ví của anh thường xuyên trống rỗng. Nhưng anh vẫn tiếp tục đi trên con đường mình đã chọn. Thái độ sống như vậy đã làm cho Kenzō trở thành một hiện thân của người trí thức, với bản chất cố hữu định hình nên thân phận của họ, cùng tất cả những hệ lụy kèm theo. Không hấp dẫn như một bữa ăn ngon trước mắt, cũng không đầy mãnh lực như của cải bạc tiền, sự tồn tại của người trí thức thầm lặng và vô hình như một loại dưỡng khí cho đời sống. Nhưng, phải chăng như cái lọ rỗng thì mới cắm được hoa, cuộc đời vẫn không thể thiếu một lớp người thầm lặng và mong manh như vậy?
“Văn phong tiểu thuyết của ông thể hiện rõ phong thái trầm tư của người trí thức. Trầm tư trước bàn viết. Trầm tư trên đường đi. Trầm tư khi chứng kiến những biểu hiện kỳ quặc của con người. Trầm tư với những tham vọng và cảm giác bất lực của cá thể nhỏ nhoi trong dòng đời cuộn chảy. Lối viết đặc thù ấy cứ như thể hiện rằng tác giả chẳng buồn tạo ra kịch tính trong tác phẩm, chẳng cần dụng công cho cốt truyện, chẳng để tâm xem câu chuyện mình kể có hấp dẫn hay không. Nhưng rồi không biết tự lúc nào, phong thái trầm tư của nhân vật cuốn người đọc vào thế giới bên trong tác phẩm. Đi theo bước chân của nhân vật, nhìn theo cái nhìn của nhân vật, người đọc cũng trở thành một lữ khách trầm tư, để rồi thỉnh thoảng chợt thấy những sự vật sự việc lâu nay vẫn tồn tại quanh mình hiển lộ trong một vầng sáng mới. Thế giới ấy không giống như một tòa nhà đồ sộ đã được xây hoàn chỉnh để người đọc chiêm ngưỡng và đánh giá, một khách thể sừng sững trước mắt người đọc, mà như một lối cỏ tình cờ mở ra trước mắt để người đọc đi vào, dẫn người đọc bước đi và quan sát thế giới quanh mình một cách tự nhiên như người ta đang sống.” – Dịch giả Lam Anh.')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0034', N'Cuốn Theo Chiều Gió', 'A031','C011', 'C001', 'C023', N'Lấy bối cảnh thời Nội chiến và tái thiết với các cuộc chiến ác liệt, những mâu thuẫn sâu sắc về chính trị, xã hội và cảnh đói nghèo sau chiến tranh, Cuốn theo chiều gió kể về Scarlett O’Hara, cô tiểu thư mắt xanh với dòng máu Ireland kiêu hãnh. Từ cô thiếu nữ mười sáu tuổi sống trong nhung lụa, bồng bột theo đuổi tình yêu, Scarlett đã đi qua những tháng ngày tuyệt vọng nhất, nếm trải mất mát, để cứu lấy mảnh đất Tara thân yêu, cứu lấy gia đình. Nhưng mặc cho phong ba bão táp của cuộc đời, nàng vẫn giữ đó niềm lạc quan vô tận. Và giữa thời thế loạn lạc, bên cạnh nàng vẫn có một Rhett Butler ngang tàng và bất cần nhưng luôn dành cho Scarlett tình yêu và sự dung túng, một Melanie Hamilton dịu dàng thương mến đã đồng hành với nàng qua mọi đau thương, cũng như một Ashley Wilkes hiền hòa luôn đắm chìm trong hoài niệm. Tất cả họ đã sống, đã yêu và đã tạo nên những hình tượng văn chương bất hủ, xóa nhòa mọi chuẩn mực, khiến người đọc vừa yêu vừa ghét, vừa nhớ mãi không quên.
Là một trong những tác phẩm được yêu thích nhất mọi thời đại, Cuốn theo chiều gió đã họa nên một giai đoạn lịch sử bi tráng của nước Mỹ, cả trong huy hoàng phồn vinh lẫn lụi tàn suy kiệt, để thấy ở đó con người với tất cả ưu, khuyết, và tình yêu với tất cả trẻ trung, khờ dại, có lúc lạc đường vì hư ảo, nhưng sau cùng vẫn luôn là tình yêu.')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0035', N'Kẻ trộm sách', 'A032','C001', 'C020', 'C000', N'Kẻ trộm sách – tác phẩm của nhà văn Úc Markus Zusak xuất bản năm 2005 đã làm mưa làm gió trên bảng xếp hạng những cuốn sách bán chạy nhất của The New York Times hơn 100 tuần liên tiếp, trở thành một tác phẩm kinh điển, một sự lựa chọn của hệ thống các thư viện trường học của Anh và Mỹ. Kẻ trộm sách khi mới ra đời đã lập tức gây ngạc nhiên cho những cây bút phê bình văn học trên thế giới và làm hàng triệu cặp mắt phải nhòa lệ.
Chọn một đề tài tưởng như đã có quá nhiều cây bút đào xới – cuộc chiến tranh thế giới lần thứ 2 – nhưng Markus Zusak vẫn gây bất ngờ cho người đọc. Người kể chuyện trong tác phẩm này là Thần Chết – một “gương mặt” quen thuộc của chiến tranh, gắn liền với cái chết, với sự bi thương, sự tăm tối. Nhưng câu chuyện mà thần chết kể ra, về sự dữ dội của những gì con người gây ra đối với chính đồng loại của họ thì đến ngay cả Thần Chết cũng phải rùng mình. Lật giở những trang sách, người đọc như bước vào cuộc trò chuyện với Thần Chết, một nhân vật có khiếu hài hước, với một lời cảnh báo nho nhỏ đầy hóm hỉnh ngay khi mở đầu câu chuyện rằng “Bạn sẽ chết”. Đây là một câu chuyện với quá nhiều cái chết nhưng cũng đầy ắp tình yêu thương và thấm đẫm tính nhân văn.')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0036', N'Kafka Bên Bờ Biển', 'A001','C001', 'C020', 'C000', N'Kafka bên bờ biển có hai câu chuyện song song. Một kể về cậu bé Kafka Tamura, một kể về lão già Nakata.
Kafka Tamura luôn có một bản ngã là Quạ theo bên cạnh. Cậu bé mười lăm tuổi này sống với cha sau khi mẹ và chị gái bỏ đi. Cậu luôn bị một lời nguyền của cha ám ảnh: mày sẽ ngủ với mẹ và chị gái mày sau khi giết cha. Kinh sợ, Kafka bỏ nhà ra đi. Cậu chìm đắm trong một thư viện sách khổng lồ ở Takamatsu. Rồi những chuyện bí ẩn xảy ra, cậu gặp cô gái Sakura và bà Miss Saeki, những người mà cậu luôn băn khoăn không biết có phải là chị và mẹ mình. Bố Kafka bị giết, và cậu nghĩ, không biết có phải lời nguyền đã ứng?
Trong khi đó, ở bên kia bờ biển, ông già Nakata cũng có một cuộc hành trình đến Takamatsu. Bị một tai nạn từ nhỏ, Nakata mất trí nhớ và khả năng đọc, viết; tuy nhiên bù lại ông có thể giao tiếp với loài mèo. Vì thế ông nhận sứ mệnh đi tìm con quỷ giết mèo hàng loạt, tìm một phiến đá bí ẩn…
 Kỳ lạ, bí ẩn, pha trộn với hiện đại, Kafka bên bờ biển khiến cho mọi con đường văn học, mọi cách tiếp cận văn học đều bàng hoàng, choáng ngợp.')
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
Values('B0037', N'Hoàng Tử Bé', 'A033','C001', 'C021', 'C011', N'Được đánh giá là một trong những cuốn sách hay nhất, thơ mộng nhất mọi thời đại, Hoàng Tử Bé kể về một phi công gặp nạn ở sa mạc Sahara vì động cơ máy bay bị hỏng nên buộc phải hạ cánh khẩn cấp, tại đây anh gặp gỡ một chú bé kỳ lạ có mái tóc vàng. Hóa ra đó là hoàng tử từ một tiểu hành tinh khác đến, đó là tiểu hành tinh B612 xa xôi và từ đây câu chuyện về cuộc đời của chú dần được hé lộ.')

INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0064', N'Gọi em bằng tên anh', 'A059', 'C001', 'C023', 'C000', N'Gọi em bằng tên anh là câu chuyện tình yêu bất ngờ và mạnh mẽ nảy nở giữa thiếu niên 17 tuổi tên Elio với Oliver, một học giả Mỹ là khách trọ mùa hè ở căn biệt thự của ba mẹ Elio tại vùng duyên hải Riviera nước Ý thập niên 1980. Trong những tuần mùa hè sôi động ấy, dòng chảy cuồn cuộn ám ảnh và đam mê bị kìm nén càng làm mãnh liệt thêm tình yêu giữa hai chàng trai trẻ. Cuốn tiểu thuyết đầu tay của André Aciman là một khúc bi ca chân thành và cảm động dành cho tình yêu con người. Một cuốn sách không thể nào quên.');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0063', N'EQ - Trí thông minh xúc cảm trong công việc', 'A058', 'C002', 'C027', 'C009', N'Trong xã hội hiện đại ngày nay, tâm lý của mỗi cá nhân đang bị ảnh hưởng rất nhiều bởi những áp lực của cuộc sống hiện đại hàng ngày.
Ở trong bối cảnh này, chỉ số EQ - hay chỉ số trí tuệ xúc cảm trở nên quan trọng hơn bao giờ hết. Biết cách làm chủ cảm xúc của mình, bạn sẽ nắm được chìa khóa để nâng cao chất lượng công việc, xây dựng những mối quan hệ tốt đẹp và nuôi dưỡng nội tâm mạnh mẽ.
Tác phẩm của Justin Bariso giúp bạn thấu hiểu tầm quan trọng của trí tuệ xúc cảm trong công việc cũng như đời sống cá nhân, từ đó cho bạn lời khuyên để không ngừng nâng cao EQ của mình. Làm thế nào để hạn chế những cảm xúc tiêu cực, khơi dậy những cảm xúc tích cực ở bản thân mình cũng như ở mọi người xung quanh? Làm thế nào để tránh khỏi những tình huống khó xử và thậm chí, xoay chuyển tình thế để chúng trở nên có lợi cho mình? Làm thế nào để tạo ra tầm ảnh hưởng, phá vỡ các rào cản cảm xúc để kết nối với mọi người và xây đắp các mối quan hệ chân thành, lành mạnh và sâu sắc?... Cảm xúc có ý nghĩa vô giá trong cuộc sống mỗi người, và thông qua việc giải đáp những câu hỏi trên.');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0062', N'999 Lá thư gởi cho mình', 'A057', 'C002', 'C026', 'C027', N'Bạn có đang cảm thấy bị “quá tải” với cuộc sống hiện tại không?
Hay là đang loay hoay chữa lành giữa những bộn bề không thể gác lại, chỉ trực chờ để cuốn mình đi?
Đã bao lâu rồi bạn chưa ngồi xuống viết những dòng nhật ký, đã bao lâu rồi bạn chưa tự gửi cho mình một lá thư viết ra những điều bạn mong muốn, viết ra những ước mơ còn dang dở, viết ra những khó khăn bạn đã hoặc đang phải trải qua và cũng không quên động viên, cổ vũ chính mình của hiện tại, nhắn nhủ đến chính mình của tương lai…
Theo dòng chảy hối hả của cuộc sống hiện nay – khi mỗi một ngày đều trôi qua nhanh chóng nhưng chẳng đọng lại được điều gì thì việc viết lách hay nhắn nhủ những lời tâm tình cho nhau càng trở thành một điều xa xỉ, dường như chẳng mấy ai nguyện làm. Nhưng không sao hết, đã có “999 lá thư gửi cho chính mình” – với Phiên bản chọn lọc, tổng hợp lại những lá thư hay nhất, những lá thư ý nghĩa nhất, chất chứa nội hàm, khả năng chữa lành cao sẽ thay những lá thư tay nói lên những điều bạn muốn giãi bày mà không thể cất tiếng, những điều trong lòng bạn chẳng biết thổ lộ với ai, cùng banj tìm lại ý nghĩa cuộc sống, tìm lại bản thân, tìm lại cả ước mơ và nhiệt huyết mà bạn đã lỡ đánh rơi trên con đường trưởng thành vội vã.
Và cũng không chỉ dừng lại ở việc mang nội dung ý nghĩa, sâu sắc nhất, những lá thư được chọn lọc kỹ càng trong sách còn được trình bày dưới phương thức song ngữ Trung – Việt như một cách biểu đạt trọn vẹn tâm tư và tình cảm của tác giả đến với độc giả, để cuốn sách không chỉ là một phương thuốc chữa lành hữu hiệu cho tâm hồn mà còn là một ấn phẩm tuyệt vời cho việc trau dồi ngoại ngữ, bổ sung kiến thức, để bạn không chỉ có một vẻ ngoài rạng rỡ mà còn tỏa sáng cả trong nội tâm, làm một người không chỉ mạnh mẽ còn có tài hoa, giúp bạn nở rộ, làm chủ sinh mệnh của chính mình.');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0061', N'Tối giản tâm trí', 'A056', 'C009', 'C007', 'C027', N'Tất cả chúng ta đều có lúc suy nghĩ tiêu cực. Màn độc thoại nội tâm này là một phần tự nhiên của tâm trí con người. Nó luôn diễn ra bất kể đêm ngày, nhắc nhở bạn về mấy món đồ lặt vặt phải mua, chê trách bạn vì đã bỏ lỡ sinh nhật của em gái, hoặc khiến bạn cảm thấy lo lắng khi nghe được những tin tức giật gân (ví dụ: chính trị, môi trường hay kinh tế). Dù mang tính tiêu cực, trung tính hay tích cực, những ý nghĩ đó cũng khiến tâm trí chúng ta bề bộn, giống như căn nhà sẽ trở nên bề bộn khi có quá nhiều món đồ. Màn độc thoại liên tục bên trong bạn khiến bạn bị phân tâm khỏi những gì xảy ra xung quanh ngay lúc này. Nó khiến bạn bỏ lỡ những trải nghiệm đầy giá trị và hủy hoại niềm vui trong hiện tại.
Với mục đích truyền tải đến bạn các thói quen, hành động và lối suy nghĩ mà bạn có thể sử dụng để dọn dẹp mớ hỗn độn trong tâm trí – thứ đang ngăn bạn tập trung và tĩnh tâm hơn. cuốn sách Tối giản tâm trí sẽ cung cấp cho bạn nguyên lý mà những hành động thực tế dựa trên cơ sở khoa học có thể tạo nên những thay đổi lâu dài và thực chất nếu được thực hiện thường xuyên.');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0060', N'Nhật kí Đặng Thùy Trâm', 'A055', 'C007', 'C027', 'C000', N'Một cuốn nhật kí nhặt được bên xác của một nữ Việt Cộng đã suýt bị người lính Mỹ ném vào lửa, nhưng người phiên dịch đã khuyên anh ta nên giữ lại vì "trong đó có lửa". Nhật kí Đặng Thùy Trâm là những ghi chép hàng ngày của một người nữ bác sĩ về cuộc sống của chị nơi chiến tuyến. Cuốn nhật kí là thế giới riêng của người trí thức nhạy cảm mà không yếu đuối, tha thiết với cuộc sống mà không hề sợ hãi trước những gian nan. Ở đó ta vẫn gặp những băn khoăn trăn trở trước tình yêu, trước cuộc sống phức tạp hàng ngày, những nỗi buồn, nỗi nhớ nhung, sự cô đơn của một người con gái, nhưng đồng thời chúng ta cũng thấy được một ý chí mãnh liệt, những lời nói tự động viên cảnh tỉnh, một lòng can đảm phi thường - những điều đã làm nên một thế hệ anh hùng.');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0059', N'Người Giàu Có Nhất Thành Babylon', 'A054', 'C002', 'C014', 'C027', N'Trước mắt bạn, tương lai đang trải rộng con đường dẫn tới những miền đất xa xôi đầy hứa hẹn. Trên con đường đó, bạn háo hức, mong muốn thực hiện nhiều ước mơ, dự định, khát khao… của riêng mình.
Để những nguyện vọng của mình được thực hiện, ít nhất bạn phải thành công về mặt tiền bạc. Quyển sách này sẽ giúp bạn biết cách vận dụng những nguyên lý quan trọng để phát triển tài chính. Hãy để cuốn sách dẫn dắt bạn đi từ một hoàn cảnh khó khăn, tiêu biểu là một cái túi lép xẹp, đến một cuộc sống đầy đủ và hạnh phúc, tiêu biểu là một túi tiền căng phồng, sung túc
Khi nói đến tiền bạc, chúng ta thường đề cập đến quy luật trọng trường và nó luôn phổ quát và bất biến trong mọi trường hợp. Trải qua thời gian dài và phát triển, quy luật này đã được trải nghiệm và đúc rút thành những bí quyết không chỉ đảm bảo cho bạn một túi tiền đầy, mà còn giúp cho bạn có một cuộc sống cân bằng để có thể phát triển mỹ mãn hơn những tiềm năng của bản thân trong các lĩnh vực khác của cuộc sống. Bởi trên thực tế, không ai có thể phủ nhận rằng sự dồi dào về vật chất có thể làm cho đời sống con người trở nên tốt đẹp hơn. Riêng trong lĩnh vực kinh doanh, sức mạnh tài chính là phương tiện chủ yếu để đo lường mức độ thành đạt của các doanh nhân.
Ngày nay, tiền bạc vẫn có những ảnh hưởng lớn đối với cuộc sống con người, cũng giống như cách đây năm ngàn năm nó đã chi phối mạnh mẽ cuộc sống của cư dân vương quốc Babylon, thúc đẩy họ tìm hiểu và nắm bắt các quy luật tạo ra tiền, nhằm có được một cuộc sống sung túc và sang trọng bậc nhất.');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0058', N'Đời ngắn đừng ngủ dài', 'A053', 'C027', 'C002', 'C000', N'“Mọi lựa chọn đều giá trị. Mọi bước đi đều quan trọng. Cuộc sống vẫn diễn ra theo cách của nó, không phải theo cách của ta. Hãy kiên nhẫn. Tin tưởng. Hãy giống như người thợ cắt đá, đều đặn từng nhịp, ngày qua ngày. Cuối cùng, một nhát cắt duy nhất sẽ phá vỡ tảng đá và lộ ra viên kim cương. Người tràn đầy nhiệt huyết và tận tâm với việc mình làm không bao giờ bị chối bỏ. Sự thật là thế.”
Bằng những lời chia sẻ thật ngắn gọn, dễ hiểu về những trải nghiệm và suy ngẫm trong đời, Robin Sharma tiếp tục phong cách viết của ông từ cuốn sách Điều vĩ đại đời thường để mang đến cho độc giả những bài viết như lời tâm sự, vừa chân thành vừa sâu sắc.');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0057', N'5 Centimet Trên Giây', 'A052', 'C001', 'C023', 'C000', N'5cm/s không chỉ là vận tốc của những cánh anh đào rơi, mà còn là vận tốc khi chúng ta lặng lẽ bước qua đời nhau, đánh mất bao cảm xúc thiết tha nhất của tình yêu.
Bằng giọng văn tinh tế, truyền cảm, 5 centimet trên giây mang đến những khắc họa mới về tâm hồn và khả năng tồn tại của cảm xúc, bắt đầu từ tình yêu trong sáng, ngọt ngào của một cô bé và cậu bé. Ba giai đoạn, ba mảnh ghép, ba ngôi kể chuyện khác nhau nhưng đều xoay quanh nhân vật nam chính, người luôn bị ám ảnh bởi kí ức và những điều đã qua…
Khác với những câu chuyện cuốn bạn chạy một mạch, truyện này khó mà đọc nhanh. Ngón tay bạn hẳn sẽ ngừng lại cả trăm lần trên mỗi trang sách. Chỉ vì một cử động rất khẽ, một câu thoại, hay một xúc cảm bất chợt có thể sẽ đánh thức những điều tưởng chừng đã ngủ quên trong tiềm thức, như ngọn đèn vừa được bật sáng trong tâm trí bạn. Và rồi có lúc nó vượt quá giới hạn chịu đựng, bạn quyết định gấp cuốn sách lại chỉ để tận hưởng chút ánh sáng từ ngọn đèn, hay đơn giản là để vết thương trong lòng mình có thời gian tự tìm xoa dịu.');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0056', N'Những điều hoàng tử bé nói với tôi', 'A051', 'C002', 'C007', 'C000', N'Những điều Hoàng tử bé nói với tôi là một ấn phẩm của Bloom Books để nhắc nhớ về chàng hoàng tử bé của chúng ta. Với hai phiên bản đai màu đỏ và xanh tương ứng với hai chiếc thiệp xinh xắn tặng kèm, Bloom Books mong muốn lan tỏa những bài học và thông điệp sâu sắc mà Hoàng tử bé gửi gắm.
Cuốn sách là những chiêm nghiệm, những bài học rút ra từ cuốn sách kinh điển Hoàng tử bé. Những bài học của hoàng tử bé được lý giải một cách thật gần gũi và sâu sắc. Hãy giải thoát bản thân khỏi ánh nhìn của người khác, chấp nhận đôi khi bị hiểu lầm, dành thời gian để sống, biết yêu thương và khiêm nhường… Nếu đôi khi, bạn cảm thấy lạc lõng trong một thế giới đang chuyển động quá nhanh khiến bạn không còn nhận ra chính mình, hãy làm như hoàng tử bé: Hãy tìm đứa trẻ đang ngủ yên trong bạn!');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0055', N'Sự im lặng của bầy cừu', 'A050', 'C001', 'C029', 'C030', N'Những cuộc phỏng vấn ở xà lim với kẻ ăn thịt người ham thích trò đùa trí tuệ, những tiết lộ nửa chừng hắn chỉ dành cho kẻ nào thông minh, những cái nhìn xuyên thấu thân phận và suy tư của cô mà đôi khi cô muốn lảng tránh... Clarice Starling đã dấn thân vào cuộc điều tra án giết người lột da hàng loạt như thế, để rồi trong tiếng bức bối của chiếc đồng hồ đếm ngược về cái chết, cô phải vật lộn để chấm dứt tiếng kêu bao lâu nay vẫn đeo đẳng giấc mơ mình: tiếng kêu của bầy cừu sắp bị đem đi giết thịt.
Sự im lặng của bầy cừu hội tụ đầy đủ những yếu tố làm nên một cuốn tiểu thuyết trinh thám kinh dị xuất sắc nhất: không một dấu vết lúng túng trong những chi tiết thuộc lĩnh vực chuyên môn, với các tình tiết giật gân, cái chết luôn lơ lửng, với cuộc so găng của những bộ óc lớn mà không có chỗ cho kẻ ngu ngốc để cuộc chơi trí tuệ trở nên dễ dàng. Bồi đắp vào cốt truyện lôi cuốn đó là cơ hội được trải nghiệm trong trí não của cả kẻ gây tội lẫn kẻ thi hành công lý, khi mỗi bên phải vật vã trong ngục tù của đau đớn để tìm kiếm, khẩn thiết và liên tục, một sự lắng dịu cho tâm hồn.');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0054', N'Mật mã Da Vinci', 'A049', 'C001', 'C029', 'C011', N'Trong khi đang công tác ở Pari, nhà biểu tượng học của trường Đại học Harvard, Robert Langdon nhận được một cuộc điện thoại khẩn cấp lúc tối muộn. Người quản lý lớn tuổi của bảo tàng Louvre đã bị sát hại trong bảo tàng, một mật mã khó hiểu được tìm thấy gần thi thể nạn nhân. Khi Langdon và nhà mật mã học người Pháp tài năng, Sphie Neveu, giải mã những bí ẩn kỳ quái này, họ đã hết sức sửng sốt khi phát hiện ra một chuỗi các manh mối được giấu trong các tác phẩm của Da Vinci những đầu mối rõ ràng để mọi người nhìn thấy nhưng lại được nguỵ trang một cách tài tình bởi người hoạ sĩ. 
Sự khẩn cấp tăng lên khi Langdon hé mở một mối liên hệ làm người ta phải giật mình: Người quản lý quá cố tham gia Tu viện của dân Do Thái - một tổ chức bí mật có thật mà trong số các thành viên của nó cả Ngài Isaac Newton, Bottcelli, Victor Hugo, và Da Vinci. Langdon có linh cảm rằng họ đang theo đuổi một bí mật lịch sử gây kinh ngạc, đã chứng minh trong nhiều thế kỷ là sáng tỏ và cũng rất nguy hiểm. Trong cuộc chạy đua điên cuồng qua Pari và các nơi khác, Langdon và Neveu nhận thấy rằng học đang đối chọi với một kẻ buôn đồ cổ đầy thế lực giấu mặt, hắn luôn xuất hiện để chặn trước mọi hàng động của họ. Trừ khi họ có thể giải mã câu đố hóc búa ấy, nếu không bí mật của Tu viện - và một sự thật lịch sử gây chấn động - sẽ biến mất mãi mãi. ');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0053', N'Luật im lặng', 'A003', 'C001', 'C007', 'C000', N'OMERTÀ (Luật im lặng) là luật danh dự của người Sicily cấm tố giác những hành động tội lỗi của những người liên quan. Luật im lặng của người Sicily (Ý) là nền tảng cho lòng trung thành của tổ chức Mafia từ nhiều thế kỷ qua, nhưng giờ đây nó đang dần trở thành di tích mang tính biểu trưng cho dĩ vãng. Lòng trung thành có thể im lặng nhưng tiền lại biết nói.
Tại New York - Một ông Trùm đã về hưu - Trùm Aprile bị ám sát và không ai lên tiếng. Cháu trai ông ta: Astorre và giám đốc FBI New York: Cilke cùng tham gia điều tra vụ án. Nhưng sự im lặng cứ lan rộng ra như căn bệnh truyền nhiễm. Các băng đảng đối địch im lặng, các ông chủ nhà băng im lặng, rồi cả tòa án cũng im lặng. Để rồi khi tiền bắt đầu lên tiếng...
Kẻ nào có thể ra lệnh giết ông Trùm Aprile và vì mục đích gì? Một cuộc trả thù cho cái chết của ông Trùm diễn ra do Astorre thực hiện diễn ra ra sao, xin mời bạn tìm đọc truyện Luật im lặng sẽ rõ.');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0052', N'Đọc Vị Bất Kỳ Ai', 'A048', 'C009', 'C007', 'C006', N'Hãy chiếm thế thượng phong trong việc chủ động nhận biết điều cần tìm kiếm - ở bất kỳ ai bằng cách “thâm nhập vào suy nghĩ” của người khác. ĐỌC VỊ BẤT KỲ AI là cẩm nang dạy bạn cách thâm nhập vào tâm trí của người khác để biết điều người ta đang nghĩ. Cuốn sách này sẽ không giúp bạn rút ra các kết luận chung về một ai đó dựa vào cảm tính hay sự võ đoán. Những nguyên tắc được chia sẻ trong cuốn sách này không đơn thuần là những lý thuyết hay mẹo vặt chỉ đúng trong một số trường hợp hoặc với những đối tượng nhất định. Các kết quả nghiên cứu trong cuốn sách này được đưa ra dựa trên phương pháp S.N.A.P - cách thức phân tích và tìm hiểu tính cách một cách bài bản trong phạm vi cho phép mà không làm mếch lòng đối tượng được phân tích. Phương pháp này dựa trên những phân tích về tâm lý, chứ không chỉ đơn thuần dựa trên ngôn ngữ cử chỉ, trực giác hay võ đoán.');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0051', N'Quẳng Gánh Lo Đi & Vui Sống', 'A047', 'C005', 'C006', 'C000', N'Quẳng Gánh Lo Đi Và Vui Sống là cuốn sách mà cái tên đã nói lên tất cả nội dung chuyển tải trên những trang giấy.
Bất kỳ ai đang sống đều sẽ có những lo lắng thường trực về học hành, công việc, những hoá đơn, chuyện nhà cửa,… Cuộc sống không dễ dàng giải thoát bạn khỏi căng thẳng, ngược lại, nếu quá lo lắng, bạn có thể mắc bệnh trầm cảm. Quẳng Gánh Lo Đi Và Vui Sống khuyên bạn hãy khóa chặt dĩ vãng và tương lai lại để sống trong cái phòng kín mít của ngày hôm nay. Mọi vấn đề đều có thể được giải quyết, chỉ cần bạn bình tĩnh và xác định đúng hành động cần làm vào đúng thời điểm.
Nói thì có vẻ dễ nhưng những vấn đề liên quan đến các trạng thái tinh thần chẳng bao giờ dễ giải quyết. Chấm dứt lo lắng là điều không thể nhưng bớt đi sự lo lắng thì có thể, chỉ cần bạn đủ quyết tâm.');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0050', N'Lão Hạc', 'A046', 'C011', 'C022', 'C000', N'Lão Hạc là một truyện ngắn của nhà văn Nam Cao được viết năm 1943. Tác phẩm được đánh giá là một trong những truyện ngắn khá tiêu biểu của dòng văn học hiện thực, nội dung truyện đã phần nào phản ánh được hiện trạng xã hội Việt Nam trong giai đoạn trước Cách mạng tháng Tám.
Lão Hạc, một người nông dân chất phác, hiền lành. Lão góa vợ và có một người con trai nhưng vì quá nghèo nên không thể lấy vợ cho người con trai của mình. Người con trai lão vì thế đã rời bỏ quê hương để đến đồn điền cao su làm ăn kiếm tiền. Lão luôn trăn trở, suy nghĩ về tương lai của đứa con. Lão sống bằng nghề làm vườn, mảnh vườn mà vợ lão đã mất bao công sức để mua về và để lại cho con trai lão. So với những người khác lúc đó, gia cảnh của lão khá đầy đủ, tuy nhiên do ốm yếu hơn hai tháng và cũng vì trận bão mà lão không có việc gì để làm. Lão đã rất dằn vặt bản thân mình khi mang một "tội lỗi" là đã nỡ tâm "lừa một con chó". Lão đã khóc rất nhiều với ông giáo (người hàng xóm thân thiết của lão).');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0049', N'Góc Sân và Khoảng Trời', 'A045', 'C021', 'C019', 'C000', N'Góc sân và khoảng trời là tập thơ của Trần Đăng Khoa được xuất bản lần đầu tiên năm 1968 khi tác giả mới 10 tuổi. Tập thơ mới đầu có tên là Từ góc sân nhà em, sau nhiều lần tái bản và chỉnh sửa, nay tập thơ tên là Góc sân và khoảng trời. Tập thơ như là những trang ký ức, nhật ký của tác giả thời thơ ấu. Tập thơ gồm có 105 bài thơ và Trường ca đánh Thần Hạn có 4 chương.');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0048', N'Những Ngày Thơ Ấu', 'A044', 'C011', 'C021', 'C001', N'“NHỮNG NGÀY THƠ ẤU” có thể coi là một tác phẩm xuất sắc. Đây là tập hồi ký về tuổi thơ ghi lại những “Rung động cực điểm của một linh hồn trẻ dại”.');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0047', N'Hà Nội 36 Phố Phường', 'A043', 'C006', 'C028', 'C000', N'Hà Nội ba mươi sáu phố phường của Thạch Lam được đánh giá là một cuốn bút ký dành riêng cho vẻ đẹp Hà Nội. Xét trong sự nghiệp sáng tác của Thạch Lam, đây cũng là một áng văn đẹp thể hiện rất rõ phong cách tâm hồn ông. Phó Tiến sĩ Vũ Tuấn Anh, phụ trách Ban văn học hiện đại, Viện Văn học Việt Nam nói: "Đặt trong bối cảnh đương thời thì Hà Nội băm sáu phố phường là một tác phẩm rất có ý nghĩa. Nó trân trọng vẻ đẹp của đất nước nói chung và Hà Nội nói riêng. Cuốn sách mỏng, xinh xắn với chỉ 70 trang nhưng cho đến nay, khi người ta nói đến Hà Nội và những tác phẩm thể hiện được tinh hoa, vẻ đẹp của Hà Nội thì người ta vẫn nhắc đến Hà Nội băm sáu phố phường. Sau khi Thạch Lam mất đến nay đã nửa thế kỷ, đã có rất nhiều sách viết về Hà Nội nhưng với sự tinh tế của mình, Hà Nội băm sáu phố phường vẫn có vị trí rất đặc biệt trong số các tác phẩm viết về Hà Nội, khiến cho người đọc không thể quên được".');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0046', N'Nhật ký trong tù', 'A042', 'C019', 'C003', 'C000', N'Chủ tịch Hồ Chí Minh là vị lãnh tụ thiên tài của Đảng và nhân dân Việt Nam, anh hùng giải phóng dân tộc, danh nhân văn hoá thế giới. Người kết tinh trong mình những phẩm chất và giá trị tinh thần cao quý nhất của giai cấp công nhân và dân tộc việt Nam. Cuộc đời, sự nghiệp của Người là một tấm gương sáng vì dân, vì nước. Trong suốt cuộc đời hoạt động cách mạng, Người đã trải qua nhiều khó khăn, gian khổ, thậm chí nguy hiểm đến tính mạng, nhưng dù bất kỳ hoàn cảnh nào. Người cũng vẫn luôn lạc quan, tin tưởng vào thắng lợi của cách mạng. Tinh thần ấy thể hiện rõ trong nhiều trước tác của Người, trong đó tập thơ Nhật ký trong tù.
Đây là một tập thơ chữ Hán, gồm hơn một trăm bài thơ, phần cuối có một số ghi chép về quân sự và thời sự, được Chủ tịch Hồ Chí Minh sáng tác trong thời gian hơn một năm (từ 29-8-1942 đến 10-9-1943) Người bị chính quyền địa phương của Tưởng Giới Thạch bắt giam trái phép tại các nhà tù ở tỉnh Quảng tây, Trung Quốc. Nhật ký trong tù lên án chế độc nhà tù hà khắc của chính quyền Quốc dân Đảng, thể hiện tinh thần lạc quan cách mạng và tình cảm nhân đạo cộng sản chủ nghĩa cao đẹp của Chủ tịch Hồ Chí Minh. Tập thơ được đánh giá là một văn kiện lịch sử quan trọng, một tác phẩm văn học xuất sắc, có tác dụng giáo dục sâu sắc phẩm chất và đạo đức cách mạng cho nhiều thế hệ.
Tác phẩm Nhật ký trong tù đã được xuất bản nhiều lần, được dịch và giới thiệu ở nhiều nước trên thế giới.');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0045', N'Chuyện phiếm sử học', 'A041', 'C003', 'C006', 'C000', N'“Tạ Chí Đại Trường là một nhà sử học có tính độc lập và phong cách riêng trong nghiên cứu lịch sử. Ông có những công trình nghiên cứu sâu sắc trên phương pháp luận sử học nghiêm túc mà tiêu biểu là Lịch sử nội chiến Việt Nam từ 1771 đến 1802. Các tác phẩm của Tạ Chí Đại Trường mang nặng tính suy ngẫm lịch sử, gần như một thứ triết lý lịch sử, như Những bài dã sử Việt, hay Thần, người và đất Việt. Tạ Chí Đại Trường luôn nhìn lịch sử Việt Nam với tấm lòng của một con người Việt Nam.”- GS Phan Huy Lê
“Khi chúng ta đọc các tác phẩm của Tạ Chí Đại Trường, chúng ta thấy có một sự tìm kiếm sự thật rất là công phu, có sự nhận định và lý luận rất thẳng thắn. Nó khác với các quan điểm của các sử quan ngày trước, và đến mãi sau này nữa, là dùng lịch sử như là một dụng cụ để củng cố chế độ đương quyền…”- Nguyễn Gia Kiểng
“Tạ Chí Đại Trường còn là một ngòi bút thực thụ. Mỗi tác phẩm lịch sử của ông đều thật sự là một tác phẩm văn học đáng giá…”- Nguyên Ngọc');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0044', N'Chú Bé Mang Pyjama Sọc', 'A040', 'C001', 'C003', 'C000', N'Rất khó miêu tả câu chuyện về Chú bé mang pyjama sọc này. Thường thì chúng tôi vẫn tiết lộ vài chi tiết về cuốn sách trên bìa, nhưng trong trường hợp này chúng tôi nghĩ làm như vậy sẽ làm hỏng cảm giác đọc của bạn. Chúng tôi nghĩ điều quan trọng là bạn nên đọc mà không biết trước nó kể về điều gì.
Nếu bạn định bắt đầu đọc cuốn sách thật, bạn sẽ cùng được trải qua một hành trình với một cậu bé chín tuổi tên là Bruno (dù đây không hẳn là sách cho trẻ chín tuổi). Và chẳng sớm thì muộn bạn sẽ cùng Bruno đến một hàng rào. Những hàng rào như vậy vẫn tồn tại ở khắp nơi trên thế giới. Chúng tôi hy vọng không ai trong chúng ta phải vượt qua một hàng rào như vậy trong đời.');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0043', N'Khuyến Học', 'A039', 'C002', 'C026', 'C027', N'Khuyến học không phải là tác phẩm đồ sộ và sâu sắc nhất của ông nhưng lại là tác phẩm có ảnh hưởng sâu rộng nhất đến công chúng Nhật Bản. Khi mới đựơc in lần đầu, cuốn sách này có một số lượng ấn bản kỷ lục là 3,4 triệu bản, trong khi dân số Nhật Bản thời đó chỉ khoảng ba mươi lăm triệu người. Chỉ riêng điều đó đã cho thấy đây thực sự là cuốn sách gối đầu giường của mọi người dân Nhật trong thời kỳ Duy Tân. Kể từ năm 1942 đến năm 2000, riêng nhà xuất bản Iwanami Bunko cũng đã tái bản đến bảy mươi sáu lần.
Trong cuốn sách này, Fukizawa Yukichi đề cập tinh thần cơ bản của con người và mục đích thực thụ của học vấn. Với các chương viết về sự bình đẳng, quyền con người, ý nghĩa của nền văn học mới, trách nhiệm của nhân dân và chính phủ trong một quốc gia pháp trị... khuyến học đã làm lay chuyển tâm lý người Nhật Bản dưới thời Minh Trị. Với tuyên ngôn "trời không tạo ra người đứng trên người và cũng không tạo ra người đứng dưới người", Fukuzawa Yukichi đã gây kinh ngạc và bàng hoàng - như "không tin vào tai mình" - cho đa số người Nhật Bản vốn bị trói buộc bởi đẳng cấp, thân phận, quen phục tùng phó mặc và e sợ quan quyền suốt hàng trăm năm dưới chính thể phong kiến Mạc phủ. ');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0042', N'Tôi Tự Học', 'A038', 'C005', 'C006', 'C026', N'Sách “Tôi tự học” của tác giả Nguyễn Duy Cần đề cập đến khái niệm, mục đích của học vấn đối với con người đồng thời nêu lên một số phương pháp học tập đúng đắn và hiệu quả. Tác giả cho rằng giá trị của học vấn nằm ở sự lĩnh hội và mở mang tri thức của con người chứ không đơn thuần thể hiện trên bằng cấp. Trong xã hội ngày nay, không ít người quên đi ý nghĩa đích thực của học vấn, biến việc học của mình thành công cụ để kiếm tiền nhưng thực ra nó chỉ là phương tiện để đưa con người đến thành công mà thôi. Bởi vì học không phải để lấy bằng mà học còn để “biết mình” và để “đối nhân xử thế”.');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0041', N'Làm Sao Học Ít Hiểu Nhiều?', 'A037', 'C005', 'C006', 'C000', N'Cuốn Làm sao học ít hiểu nhiều? của bác sĩ tâm thần nổi tiếng người Nhật Bản, Zion Kabasawa, ra đời chính là để phá vỡ vòng luẩn quẩn ấy. Bằng kiến thức uyên thâm về cơ chế tiếp nhận, hấp thu và xử lý thông tin của não bộ của hơn 30 năm nghiên cứu và giảng dạy về thần kinh và tâm lý học, bác sĩ Zion Kabawwasa sẽ lý giải tận cùng bản chất của việc học. Từ đó, ông đưa ra những hướng dẫn rất thực tiễn về phương pháp học để vừa tiết kiệm công sức vừa đạt hiệu quả tối đa.và công sức. Nguyên nhân suy cho cùng là vì ham học mà không biết cách học mà thôi.');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0040', N'Thế giới phẳng - tóm lược lịch sử thế giới thế kỷ 21', 'A036', 'C006', 'C003', 'C017', N'Thế giới phẳng” của Thomas L. Friedman giống cái bánh mỳ nóng mới ra lò, người mua háo hức như đã từng háo hức với “Chiếc xe Lexus và cây ô-liu” cũng của ông ta cách đây dăm năm. “Phẳng” với ý nghĩa quá trình toàn cầu hóa kinh tế kéo theo quá trình toàn cầu hóa mọi mặt đời sống xã hội loài người trên hành tinh này đi vào “luật chơi chung”.');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0039', N'Gatsby Vĩ Đại', 'A035', 'C011', 'C001', 'C000', N'Kiệt tác Gatsby vĩ đại (1925) của văn hào Mỹ F. Scott Fitzgerald (1896-1940) là câu chuyện về chàng trai Jay Gatsby muốn thoát khỏi thân phận nghèo hèn và đặt chân vào tầng lớp cao sang mà hiện thân là một cô gái nhà giầu anh đã yêu và được yêu khi còn khoác trên vai bộ quân phục kông phân biệt đẳng cấp giầu nghèo. Qua mối tình mãnh liệt và mê muội của Gatsby, bằng một lối văn cực kỳ súc tích, đa tầng Fitzgerald đã vẽ ra một trong bức tranh cô đọng nhất, sâu sắc và giầu biểu tượng nhất về xã hội Mỹ trong những năm 1920 với đủ các mặt tàn nhẫn, giả dối, bịp bợm và ích kỷ của nó.');
INSERT INTO Books(BookID, BookName, AuthorID, CategoryID1, CategoryID2, CategoryID3, Summary)
VALUES ('B0038', N'Romeo Và Juliet', 'A034', 'C011', 'C001', 'C023', N'Romeo và Juliet là cuốn tiểu thuyết kinh điển kể về câu chuyện tình yêu hay nhất mọi thời đại. Một chuyện tình oan trái có thật thời Trung Cổ tại Italy được Shakespeare viết lên. Tác phẩm trở thành vở kịch xuất sắc, nổi tiếng nhất của tác giả, dàn dựng lại trên nhiều sân khấu. Cho đến nay, chuyện tình của Romeo và Juliet vẫn khiến nhiều con tim thổn thức khi đọc.');

